aa_dict = {'ALA':'A',
           'ARG':'R',
           'ASN':'N',
           'ASP':'D',
           'ASX':'B',
           'CYS':'C',
           'GLU':'E',
           'GLN':'Q',
           'GLX':'Z',
           'GLY':'G',
           'HIS':'H',
           'ILE':'I',
           'LEU':'L',
           'LYS':'K',
           'MET':'M',
           'PHE':'F',
           'PRO':'P',
           'SER':'S',
           'THR':'T',
           'TRP':'W',
           'TYR':'Y',
           'VAL':'V'}

aa_reg_str = '|'.join([key for key in aa_dict])
